[build]
  publish = "."  # Tells Netlify to publish from the root directory
  command = ""   # No build step required

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
